version: '3.0'

services:
  employee-service:
    image: employee-service
    container_name: employee-service
    ports:
      - "8081:8081"
  departament-service:
    image: department-service
    container_name: departament-service
    ports:
      - "8082:8082"
  gateway-service:
    image: gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - employee-service
      - departament-service
